name: Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Build and test the project.
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1

      # Determines the most up-to-date Hytale server version. Outputs the version string to a file
      # in `.runner/version`.
      - name: Determine server version
        env:
          HYTALE_DOWNLOADER_CREDENTIALS: ${{ secrets.HYTALE_DOWNLOADER_CREDENTIALS }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

        # Run `gh secret list` first to immediately fail the build if our GH_TOKEN has expired. This
        # prevents us from ending up with stale data inside `HYTALE_DOWNLOADER_CREDENTIALS`, since
        # if the `gh` command fails it means we didn't update the stored value of the secret.
        run: |
          gh secret list > /dev/null
          printf %s "$(pwd)/.runner" > .hytale
          
          mkdir .runner && cd .runner
          printf %s "$HYTALE_DOWNLOADER_CREDENTIALS" | base64 -d > .hytale-downloader-credentials.json
          wget 'https://downloader.hytale.com/hytale-downloader.zip' -O downloader.zip
          unzip downloader.zip
          chmod +x hytale-downloader-linux-amd64
          
          set +e
          ./hytale-downloader-linux-amd64 -skip-update-check -patchline pre-release -print-version > version
          exit_code=$?
          set -e
          
          base64 -w 0 .hytale-downloader-credentials.json | gh secret set HYTALE_DOWNLOADER_CREDENTIALS
          exit "$exit_code"

      # Restores the game files from cache, to avoid needing to re-download. Uses the hash of
      # `.runner/version` as a cache key.
      - name: Cache server files
        id: cache-server-files
        uses: &cache actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # 5.0.3
        with:
          key: hytale-server-files-${{ hashFiles('.runner/version') }}
          enableCrossOsArchive: true
          path: |
            .runner/Assets.zip
            .runner/Server/HytaleServer.jar
            .runner/Server/HytaleServer.aot

      # If the above was a cache miss, we have to download a new version of the game to build
      # against.
      - name: Download and unzip server files
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: steps.cache-server-files.outputs.cache-hit != 'true'
        run: |
          gh secret list > /dev/null
          cd .runner
          
          set +e
          ./hytale-downloader-linux-amd64 -skip-update-check -patchline pre-release -download-path game.zip
          exit_code=$?
          set -e
          
          base64 -w 0 .hytale-downloader-credentials.json | gh secret set HYTALE_DOWNLOADER_CREDENTIALS
          [ "$exit_code" -eq 0 ] || exit "$exit_code"
          
          unzip game.zip

      # We need to use a separate cache action for the convention plugin specifically: setup-gradle
      # does NOT do this automatically.
      - name: Cache buildSrc
        uses: *cache
        with:
          # Key is based off of the hash of all the script files.
          key: gradle-buildSrc-${{ hashFiles('buildSrc/*.gradle.kts', 'buildSrc/src/**/*') }}

          # The OS should not matter for these files.
          enableCrossOsArchive: true

          # These directories prevent ':buildSrc:jar' from being invalidated.
          path: |
            ./buildSrc/build/classes
            ./buildSrc/build/libs
            ./buildSrc/build/tmp

      - name: Set up JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # 5.2.0
        with:
          java-version: '25'
          distribution: 'temurin'

      # This step performs caching by default. As recommended by
      # https://community.gradle.org/github-actions/docs/setup-gradle/, we avoid using
      # `cache: 'gradle'` for actions/setup-java above as this step performs its own, more
      # effective, caching.
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # 5.0.0
        with:
          # We need to provide this secret key for the configuration cache to be cached between
          # builds.
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      # `check` runs Spotless and unit tests, `syncPlugins` collects all plugins in the `run`
      # directory.
      - name: Run unit tests and assemble plugins
        run: ./gradlew check syncPlugins

      # Integration tests are run by booting the server and executing the command
      # `integration_test`. Tests are considered to have failed if this is a non-zero exit code.
      # Note: in the future, we will also want to add --validate-assets, but at the moment even
      # vanilla Hytale does not pass their own asset validation checks; we will have to wait.
      - name: Run integration tests
        run: |
          mkdir .runner/Server/mods
          cp run/mods/*.jar .runner/Server/mods/
          
          cd .runner/Server
          ENABLE_INTEGRATION_TESTS=true java -XX:AOTCache=HytaleServer.aot --enable-native-access=ALL-UNNAMED -jar HytaleServer.jar --assets ../Assets.zip --disable-sentry --auth-mode=insecure --boot-command=integration_test --boot-command=stop