name: Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Build and test the project.
  build:
    runs-on: ubuntu-latest
    outputs:
      plugin: ${{ steps.upload-plugin.outputs.artifact-id }}

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1

      # We need to use a separate cache action for the convention plugin specifically: setup-gradle
      # does NOT do this automatically.
      - name: Cache buildSrc
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # 5.0.1
        with:
          # Key is based off of the hash of all the script files.
          key: gradle-buildSrc-${{ hashFiles('buildSrc/*.gradle.kts', 'buildSrc/src/**/*') }}

          # The OS should not matter for these files.
          enableCrossOsArchive: true

          # These directories prevent ':buildSrc:jar' from being invalidated.
          path: |
            ./buildSrc/build/classes
            ./buildSrc/build/libs
            ./buildSrc/build/tmp

      - &set-up-jdk
        name: Set up JDK 25
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # 5.0.1
        with:
          java-version: '25'
          distribution: 'temurin'

      # This step performs caching by default. As recommended by
      # https://community.gradle.org/github-actions/docs/setup-gradle/, we avoid using
      # `cache: 'gradle'` for actions/setup-java above as this step performs its own, more
      # effective, caching.
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # 5.0.0
        with:
          # We need to provide this secret key for the configuration cache to be cached between
          # builds.
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Ensure lack of file conflicts
        run: |
          ! test -e HytaleDownloader
          ! test -e game.zip
          ! test -e Assets.zip
          ! test -e Server 
          ! test -e .hytale

      - name: Determine game version
        env:
          HYTALE_DOWNLOADER_CREDENTIALS: ${{ secrets.HYTALE_DOWNLOADER_CREDENTIALS }}
        run: &game-version-command |
          mkdir HytaleDownloader
          cd HytaleDownloader
          
          wget 'https://downloader.hytale.com/hytale-downloader.zip' -O downloader.zip
          unzip downloader.zip
          chmod +x hytale-downloader-linux-amd64
          printf %s "$HYTALE_DOWNLOADER_CREDENTIALS" > .hytale-downloader-credentials.json
          ./hytale-downloader-linux-amd64 -skip-update-check -print-version > game_version

      - name: Cache server files
        id: cache-server-files
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # 5.0.1
        with:
          key: hytale-server-files-${{ hashFiles('HytaleDownloader/game_version') }}
          path: |
            ./Server/HytaleServer.jar
            ./Assets.zip   

      - &download-and-extract-game
        name: Download and extract game.zip
        if: steps.cache-server-files.outputs.cache-hit != true
        run: |
          cd HytaleDownloader
          ./hytale-downloader-linux-amd64 -skip-update-check -download-path ../game.zip
          cd ..
          unzip game.zip

      - name: Build project
        run: |
          printf %s "$(pwd)" > .hytale
          ./gradlew build

      - name: Upload plugin
        id: upload-plugin
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # 6.0.0
        with:
          name: plugin
          path: ./main/build/libs/main.jar

          # It's an error if we can't find our plugin jar.
          if-no-files-found: error

          # Jar files already use compression.
          compression-level: 0

          # Overwrite the previous file if it exists.
          overwrite: true

  # Tests that the Hytale server launches correctly with the plugin.
  launch:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    steps:
      - *set-up-jdk

      - name: Download plugin
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # 7.0.0
        with:
          artifact-ids: ${{ needs.build.outputs.plugin }}

      - name: Determine game version
        env:
          HYTALE_DOWNLOADER_CREDENTIALS: ${{ secrets.HYTALE_DOWNLOADER_CREDENTIALS }}
        run: *game-version-command

      - name: Cache server files
        id: cache-server-files
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # 5.0.1
        with:
          key: hytale-server-files-${{ hashFiles('HytaleDownloader/game_version') }}
          path: |
            ./Server/HytaleServer.jar
            ./Assets.zip

      - *download-and-extract-game

      - name: Validate assets
        run: |
          cd Server
          mkdir mods
          mv ../main.jar mods/
          java -XX:AOTCache=HytaleServer.aot -jar HytaleServer.jar --assets ../Assets.zip --auth-mode=insecure --disable-sentry --validate-assets --validate-prefabs --validate-world-gen --shutdown-after-validate