name: Dependency Submission

on:
  push:
    branches: [ "main" ]

jobs:
  # Dependency graph support.
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1

      # Same as in the build.yml workflow, but only reads from the cache.
      - name: Cache buildSrc
        uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # 5.0.2
        with:
          key: gradle-buildSrc-${{ hashFiles('buildSrc/*.gradle.kts', 'buildSrc/src/**/*', 'gradle/wrapper/*') }}
          enableCrossOsArchive: true
          path: |
            ./buildSrc/build/classes
            ./buildSrc/build/libs
            ./buildSrc/build/tmp       

      - name: Set up JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # 5.2.0
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Submit dependency graph
        uses: gradle/actions/dependency-submission@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # 5.0.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}